#!/bin/bash

BOOT0="/sys/class/gpio/gpio17"
RST="/sys/class/gpio/gpio23"
STM32FLASH='/home/pi/stm32flash/stm32flash.1'
BINFILE='/home/pi/wallaby_v8.bin'
DEV='/dev/ttyAMA0'

if [ $# -ne 0 ]; then
    BINFILE=$1
fi


#make sure we can control BOOT0 and RST
if [ ! -d "${BOOT0}" ]; then 
    echo "${BOOT0} - initializing gpio pins" 
    ./wallaby_init_gpio 
fi

if [ ! -d "${RST}" ]; then 
    echo "${RST} missing - initializing gpio pins" 
    ./wallaby_init_gpio 
fi

# set BOOT0 high so we stay in the bootloader on reboot
CMD="echo 1 > ${BOOT0}/value"
echo $CMD
eval $CMD

# reset co-processor
./wallaby_reset_coproc

# program
sleep 1 
CMD="${STM32FLASH} -v -S 0x08000000 -w ${BINFILE} ${DEV}"
echo $CMD
eval $CMD

# BOOT0 low to run program after reset
CMD="echo 0 > ${BOOT0}/value"
echo $CMD
eval $CMD
sleep 1 

# reset co-processor
./wallaby_reset_coproc
